export const TuningParts: Array<{ category: string; part: string; index: number; price?: number }> = [
    { category: 'Spoilers', part: 'spoiler', index: 0, price: 5000 },
    { category: 'Front Bumper', part: 'front-bumper', index: 1 },
    { category: 'Rear Bumper', part: 'rear-bumper', index: 2 },
    { category: 'Side Skirt', part: 'side-skirt', index: 3 },
    { category: 'Exhaust', part: 'exhaust', index: 4 },
    { category: 'Frame', part: 'frame', index: 5 },
    { category: 'Grille', part: 'grille', index: 6 },
    { category: 'Bonnet', part: 'hood', index: 7 },
    { category: 'Wing (left)', part: 'fender', index: 8 },
    { category: 'Wing (right)', part: 'fender', index: 9 },
    { category: 'Roof', part: 'roof', index: 10 },
    { category: 'Engine', part: 'engine', index: 11 },
    { category: 'Brakes', part: 'brakes', index: 12 },
    { category: 'Transmission', part: 'transmission', index: 13 },
    { category: 'Horns', part: 'horns', index: 14 },
    { category: 'Suspension', part: 'suspension', index: 15 },
    { category: 'Armor', part: 'armor', index: 16 },
    { category: '-', part: '-', index: 17 },
    { category: 'Turbo', part: 'turbo', index: 18 },
    { category: '-', part: '-', index: 19 },
    { category: 'Custom Tire Smoke', part: 'custom-tire-smoke', index: 20 },
    { category: '-', part: '-', index: 21 },
    { category: 'Xenon', part: 'xenon', index: 22 },
    { category: 'Front Wheels', part: 'wheels', index: 23 },
    { category: 'Back Wheels', part: 'back-wheels', index: 24 },
    { category: 'Plate Holders', part: 'plate-holders', index: 25 },
    { category: 'Plate Vanity', part: 'plate-vanity', index: 26 },
    { category: 'Trim Design', part: 'trim-design', index: 27 },
    { category: 'Ornaments', part: 'ornaments', index: 28 },
    { category: 'Dial Design', part: 'dial-design', index: 30 },
    { category: 'Door Interior', part: 'door-interior', index: 31 },
    { category: 'Seats', part: 'seats', index: 32 },
    { category: 'Steering Wheel', part: 'steering-wheel', index: 33 },
    { category: 'Shift Lever', part: 'shift-lever', index: 34 },
    { category: 'Plaques', part: 'plaques', index: 35 },
    { category: 'Rear Shelf', part: 'rear-shelf', index: 36 },
    { category: 'Trunk', part: 'trunk', index: 37 },
    { category: 'Hydraulics', part: 'hydraulics', index: 38 },
    { category: 'Engine Block', part: 'engine-block', index: 39 },
    { category: 'Air Filter', part: 'air-filter', index: 40 },
    { category: 'Strut Bar', part: 'strut-bar', index: 41 },
    { category: 'Arch Cover', part: 'arch-cover', index: 42 },
    { category: 'Antenna', part: 'antenna', index: 43 },
    { category: 'Exterior Parts', part: 'exterior-parts', index: 44 },
    { category: 'Tank', part: 'tank', index: 45 },
    { category: 'Door / Windows', part: 'door-windows', index: 46 },
    { category: 'Hydraulics', part: 'hydraulics', index: 47 },
    { category: 'Livery', part: 'livery', index: 48 },
    { category: 'Window Tint', part: 'tinted-window', index: 63 },
    { category: 'Wheel Color', part: 'colorwheel', index: 64 },
    { category: 'Pearl Color', part: 'colorwheel', index: 65 },
    { category: 'Primary Color', part: 'colorwheel', index: 66 },
    { category: 'Secondary Color', part: 'colorwheel', index: 67 },
    { category: 'Neon Light', part: 'neon', index: 68 },
];

export const modPrices: number[] = Array.from({ length: 160 }, (_, index) => index * 1000);
