export const debugItems = [
    {
        uid: '1',
        id: '1',
        name: 'Item 1',
        desc: 'Description 1',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 0 },
    },
    {
        uid: '2',
        id: '2',
        name: 'Item 2',
        desc: 'Description 2',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 2,
        data: { slot: 6 },
    },
    {
        uid: '3',
        id: '3',
        name: 'Item 3',
        desc: 'Description 3',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 12,
        data: { slot: 3 },
    },
    {
        uid: '4',
        id: '4',
        name: 'Item 4',
        desc: 'Description 4',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 10 },
    },
    {
        uid: '5',
        id: '5',
        name: 'Item 5',
        desc: '',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 4 },
    },
    {
        uid: '6',
        id: '6',
        name: 'Item 6',
        desc: 'Description 6',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 23 },
    },
    {
        uid: '7',
        id: '7',
        name: 'Item 7',
        desc: 'Description 7',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 12 },
    },
    {
        uid: '8',
        id: '8',
        name: 'Item 8',
        desc: 'Description 8',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 7 },
    },
    {
        uid: '9',
        id: '9',
        name: 'Item 9',
        desc: 'Description 9',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 8 },
    },
    {
        uid: '10',
        id: '10',
        name: 'Item 10',
        desc: 'Description 10',
        maxStack: 10,
        weight: 1,
        icon: 'crate',
        quantity: 1,
        data: { slot: 20 },
    },
];
